---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - appName: metal-lb
        repoPath: infra/argo-cd-apps/metal-lb
        targetRevision: metal-lb-app
  template:
    metadata:
      name: {{.appName}}
    spec:
      project: default
      source:
        repoURL: https://github.com/88lexd/website-astro
        path: {{.repoPath}}
        targetRevision: {{.targetRevision}}
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
