---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argocd
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  project: default
  source:
    repoURL: https://github.com/88lexd/website-astro
    path: infra/argo-cd-apps/metal-lb
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
