---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.17.0/manifests/install.yaml
    # `targetRevision` and `path` is ignored for HTTP(s) sources.
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
