---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj-labs/argocd-image-updater.git
    targetRevision: v0.17.0
    directory:
      # Ref: https://github.com/argoproj-labs/argocd-image-updater/tree/v0.17.0/manifests
      exclude: '{base/*}'
      include: 'install.yaml'
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
