---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  # Lets not enable `cascading deletion`.
  # Just in case it messes up ingress IP  when this Application ever needs to be converted to an ApplicationSet
  # If a real cleanup is required, I can always use the UI to delete the application with cascading deletion.
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.13.2
      helm:
        releaseName: ingress-nginx
        # Technically can use `valuesObject` but also wanted to show that values can be defined elsewhere
        valueFiles:
          - $values/infra/charts/ingress-nginx/values.yaml
    - repoURL: https://github.com/88lexd/website-astro
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
