---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  namespace: argocd
  # Lets not enable `cascading deletion`.
  # Just in case it messes up IP addresses when this Application ever needs to be converted to an ApplicationSet
  # If a real cleanup is required, I can always use the UI to delete the application with cascading deletion.
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-logs-cluster
      targetRevision: 0.0.13
      helm:
        releaseName: vlc
        # Technically can use `valuesObject` but also wanted to show that values can be defined elsewhere
        valueFiles:
          - $values/infra/charts/observability/victoria-logs-cluster/values.yaml
    - repoURL: https://github.com/88lexd/website-astro
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
