---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-svc
  labels:
    app: {{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  type: ClusterIP  # This is the default but is a good practice to define it.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-{{ .Release.Namespace }}
