# Provides the app of apps pattern for Argo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  project: default
  source:
    repoURL: https://github.com/88lexd/website-astro
    path: infra/argo-cd-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
