# Self Managed Argo
# Note: To test this on a branch, the following was ran and `targetRevision` is set to the current branch before running
# $ argocd app create argocd --file templates/app-argocd.yaml --port-forward --port-forward-namespace argocd
# Fix targetRevision and once merged use the following command to update the application again
# argocd app create argocd --file templates/app-argocd.yaml --port-forward --port-forward-namespace argocd --upsert
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  project: default
  source:
    repoURL: https://github.com/88lexd/website-astro
    path: infra/argo-cd
    targetRevision: reinstall-argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
