---
opentelemetry-operator:
  manager:
    targetAllocatorImage:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator
      # Image tag version should match the otel-operator chart App version (Check README for the command)
      # Ref: https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Ftarget-allocator
      tag: "0.136.0"
