---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-targetallocator-sa"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-targetallocator-cluster-role"
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/metrics
    - services
    - endpoints
    - pods
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["get"]

  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs: ["get", "list", "watch"]

  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]

  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-targetallocator-cluster-role-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-targetallocator-cluster-role"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-targetallocator-sa" # Service Account is created by Target Allocator
    namespace: {{ .Release.Namespace }}
