# WARNING: Only install this ONCE code has been merged!
# Otherwise the `argocd-values.yaml` will not exist and Argo will install again using default values
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.5.6
      helm:
        releaseName: argocd
        valueFiles:
          - $values/infra/argo-cd/argocd-values.yaml
    - repoURL: https://github.com/88lexd/website-astro
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
