# WARNING: Only install this ONCE code has been merged!
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.5.6
    helm:
      releaseName: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
