name: Argo Create PR Workflow

on:
  push:
    branches:
    # This branch name is created by Argo CD Image Updater by the App's annotation
    - argo-cd-image-updater

permissions:
  contents: write
  pull-requests: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          python3 scripts/gha-argocd-create-pr.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          HEAD_BRANCH: ${{ github.ref_name }}
          BASE_BRANCH: main
          PR_TITLE: "[Build] Argo bump image version"
          PR_BODY: "Argo CD Image Updater has detected a new image version. Merge PR to deploy change."
