name: Argo Create PR Workflow

on:
  push:
    branches:
    # This branch name is created by Argo CD Image Updater by the App's annotation
    - argo-cd-image-updater

permissions:
  contents: write
  pull-requests: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: argo-cd-image-updater
          title: '[Build] Argo bump image version'
          commit-message: '[build] bump image version'
