name: PR CI Workflow

on:
  pull_request:
    branches:
      - main
    paths:
    - 'astro/**'
    - 'contents/**'

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build image
      run: docker build -t astro .

    - name: Run app container
      run: |
        docker run -d --rm -p 80:80 --name app astro

    - name: Check app status
      run: |
        ENDPOINT="http://127.0.0.1/health-check"

        echo "Wait 5 seconds for server to be ready"
        sleep 5

        curl -s $ENDPOINT

        STATUS=$(curl -s $ENDPOINT | jq -r '.statusText')

        if [[ "$STATUS" == "OK" ]]; then
          echo -e "\nStatus is OK"
        else
          echo -e "\nERROR: Status is not OK"
          docker logs app
          exit 1
        fi
