name: Release Workflow

on:
  push:
    branches:
      - main

  # Remove this.. use for testing only
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Semantic version
      id: sem-ver
      uses: paulhatch/semantic-version@v5.4.0
      with:
        version_format: ${major}.${minor}.${patch}
        major_pattern: "[MAJOR]"
        minor_pattern: "[MINOR]"

    - name: Debug
      env:
        JSON: ${{ toJSON(steps.sem-ver.outputs) }}
      run: echo "${JSON}"

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: true
    #     tags: user/app:latest
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max